In [1]:
import os 
import matplotlib.pyplot as plt 
import pandas as pd 
import numpy as np 
import seaborn as sns
import joblib 
from matplotlib.colors import ListedColormap


In [2]:
import pyodbc

driver = 'SQL Server'
server = 'DS\MSSQLSERVER01'
database = 'test'



conn = pyodbc.connect(f"Driver={driver};Server={server};Database={database};Trusted_Connection=yes;")
conn

In [3]:
# class Perceptron:
#     # Declaration ETA - Learning Rate, Epoch - How Many iteration it will gone
#     def __init__(self,eta:float=None,epochs:int=None):
#         self.weights = np.random.randn(3) * 1e-4 # small random weight
#         is_training = (eta is not None) and (epochs is not None)
#         if is_training:
#             print(f"Intial Weigh before Training {self.weights}")
#         self.eta = eta
#         self.epochs = epochs

#     # Summation of weight , input and bias
#     def _z_outcome(self,input_with_bias,weights):
#         return np.dot(input_with_bias,weights)
    
#     # Activation Function
#     def activation_function(self,z):
#         return np.where(z > 0,1,0)
    
#     # Which will train the Model  - Passing X and Y
#     def fit(self,X,y):
#         self.X = X
#         self.y = y 
#         X_with_bias  = np.c_[self.X,-np.ones((len(self.X),1))]
#         print(f"X with Bias :\n{X_with_bias}")

#         for epoch in range(self.epochs):
#             print(f"for epoch >> {epoch}")
#              # Summation thing
#             z = self._z_outcome(X_with_bias,self.weights)
#               # Activation applies here
#             y_hat = self.activation_function(z)
#             print(f"Predicted Value after Forward Pass {y_hat}")
#              # Here Error You will Get
#             self.error = self.y - y_hat
#             print(f"error : {self.error}")

#             # Weight update rule 
#             self.weights = self.weights - self.eta * np.dot(X_with_bias.T,self.error)
#             print(f"Updated weights after epochs {epoch +1}/{self.epochs}:\n{self.weights}")
    
#     # Predict 
#     def predict(self,X):
#         X_with_bias  = np.c_[self.X,-np.ones((len(self.X),1))]
#         z = self._z_outcome(X_with_bias,self.weights)
#         return self.activation_function(z)


#     # Total Error    
#     def total_loss(self):
#         total_loss = np.sum(self.error)
#         print(f"total loss {total_loss}")
#         return total_loss

#     def _create_dir_return_path(self,model_dir,filename):
#         os.makedirs(model_dir,exist_ok=True)
#         return os.path.join(model_dir,filename)

#     # Saving our Train Model    
#     def save(self,filename,mode_dir=None):
#         if mode_dir is not None:
#             model_file_path = self._create_dir_return_path(mode_dir,filename)
#             joblib.dump(self,model_file_path)
#         else:
#             model_file_path = self._create_dir_return_path("model",filename)
#             joblib.dump(self,model_file_path)

#     # To Load Our Model    
#     def load(self,filepath):
#         return joblib.load(filepath)


In [4]:
class Perceptron1:
    def __init__(self, eta: float=None, epochs: int=None):
        self.weights = np.random.randn(3) * 1e-4 # small random weights
        training = (eta is not None) and (epochs is not None)
        if training:
            print(f"initial weights before training: \n{self.weights}\n")
        self.eta = eta
        self.epochs = epochs
    
    def _z_outcome(self, inputs, weights):
        return np.dot(inputs, weights)
    
    def activation_function(self, z):
        return np.where(z > 0, 1, 0)
    
    def fit(self, X, y):
        self.X = X
        self.y = y
        
        X_with_bias = np.c_[self.X, -np.ones((len(self.X), 1))]
        print(f"X with bias: \n{X_with_bias}")
        
        for epoch in range(self.epochs):
            print("--"*10)
            print(f"for epoch >> {epoch}")
            print("--"*10)
            
            z = self._z_outcome(X_with_bias, self.weights)
            y_hat = self.activation_function(z)
            print(f"predicted value after forward pass: \n{y_hat}")
            
            self.error = self.y - y_hat
            print(f"error: \n{self.error}")
            
            self.weights = self.weights + self.eta * np.dot(X_with_bias.T, self.error)
            print(f"updated weights after epoch: {epoch + 1}/{self.epochs}: \n{self.weights}")
            print("##"*10)
            
    
    def predict(self, X):
        X_with_bias = np.c_[X, -np.ones((len(X), 1))]
        z = self._z_outcome(X_with_bias, self.weights)
        return self.activation_function(z)
    
    def total_loss(self):
        total_loss = np.sum(self.error)
        print(f"\ntotal loss: {total_loss}\n")
        return total_loss
    
    def _create_dir_return_path(self, model_dir, filename):
        os.makedirs(model_dir, exist_ok=True)
        return os.path.join(model_dir, filename)
    
    def save(self, filename, model_dir=None):
        if model_dir is not None:
            model_file_path = self._create_dir_return_path(model_dir, filename)
            joblib.dump(self, model_file_path)
        else:
            model_file_path = self._create_dir_return_path("model", filename)
            joblib.dump(self, model_file_path)
    
    def load(self, filepath):
        return joblib.load(filepath)

In [5]:
AND = {
    "X1" : [0,0,1,1],
    "X2" :[0,1,0,1],
    "y" : [0,0,0,1]
}

df = pd.DataFrame(AND)

In [6]:
def prepare_data(df,target_col = "y"):
    X = df.drop("y",axis=1)
    y  = df[target_col]
    return X,y 

In [7]:
df

X1  X2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [8]:
X,y = prepare_data(df)
eta = 0.1 # 0 and 1
epoch = 10
model_and = Perceptron1(eta=eta,epochs=epoch)

initial weights before training: 
[ 1.36604055e-04  7.98030261e-05 -1.05869535e-06]



In [9]:
model_and.fit(X,y)
_ = model_and.total_loss()

X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch >> 0
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1   -1
2   -1
3    0
Name: y, dtype: int64
updated weights after epoch: 1/10: 
[-0.0998634  -0.0999202   0.29999894]
####################
--------------------
for epoch >> 1
--------------------
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights after epoch: 2/10: 
[1.36604055e-04 7.98030261e-05 1.99998941e-01]
####################
--------------------
for epoch >> 2
--------------------
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    0
2    0
3    1
Name: y, dtype: int64
updated weights after epoch: 3/10: 
[0.1001366  0.1000798  0.09999894]
####################
--------------------
for epoch >> 3
--------------------
predicted value after forward pass: 
[0 1 1 1]
error: 
0    0
1   -1
2   -1
3    0
Name: y,

In [10]:
# OR 
OR = {
    "x1": [0,0,1,1],
    "x2" : [0,1,0,1],
    "y" :[0,1,1,1]

}

df1 = pd.DataFrame(OR)

In [12]:

X, y = prepare_data(df1)

ETA = 0.1 # 0 and 1
EPOCHS = 10

model_or = Perceptron1(eta=ETA, epochs=EPOCHS)
model_or.fit(X, y)

_ = model_or.total_loss()


initial weights before training: 
[8.13528053e-05 1.15813891e-04 1.11725441e-05]

X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch >> 0
--------------------
predicted value after forward pass: 
[0 1 1 1]
error: 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 1/10: 
[8.13528053e-05 1.15813891e-04 1.11725441e-05]
####################
--------------------
for epoch >> 1
--------------------
predicted value after forward pass: 
[0 1 1 1]
error: 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 2/10: 
[8.13528053e-05 1.15813891e-04 1.11725441e-05]
####################
--------------------
for epoch >> 2
--------------------
predicted value after forward pass: 
[0 1 1 1]
error: 
0    0
1    0
2    0
3    0
Name: y, dtype: int64
updated weights after epoch: 3/10: 
[8.13528053e-05 1.15813891e-04 1.11725441e-05]
####################
--------------------
for epoch >> 3
---------

In [14]:
XOR = {
    "x1": [0,0,1,1],
    "x2": [0,1,0,1],
    "y" : [0,1,1,0]
}

df_XOR = pd.DataFrame(XOR)

df_XOR

x1  x2  y
0   0   0  0
1   0   1  1
2   1   0  1
3   1   1  0

In [15]:
X, y = prepare_data(df_XOR)

ETA = 0.1 # 0 and 1
EPOCHS = 10

model_xor = Perceptron1(eta=ETA, epochs=EPOCHS)
model_xor.fit(X, y)

_ = model_xor.total_loss()

initial weights before training: 
[ 1.43763909e-04 -6.66801743e-06 -5.41224732e-05]

X with bias: 
[[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
--------------------
for epoch >> 0
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights after epoch: 1/10: 
[-0.09985624 -0.10000667  0.19994588]
####################
--------------------
for epoch >> 1
--------------------
predicted value after forward pass: 
[0 0 0 0]
error: 
0    0
1    1
2    1
3    0
Name: y, dtype: int64
updated weights after epoch: 2/10: 
[ 1.43763909e-04 -6.66801743e-06 -5.41224732e-05]
####################
--------------------
for epoch >> 2
--------------------
predicted value after forward pass: 
[1 1 1 1]
error: 
0   -1
1    0
2    0
3   -1
Name: y, dtype: int64
updated weights after epoch: 3/10: 
[-0.09985624 -0.10000667  0.19994588]
####################
--------------------
for epoch >> 3
--------------------


In [16]:
model_and.save('model_and')

In [17]:
reload_and_model = Perceptron1().load(filepath="model/model_and")

In [19]:
reload_and_model.predict(X=[[1,0]])

array([0])

In [20]:
model_or.save('model_or')
reload_or_model = Perceptron1().load(filepath="model/model_or")

In [21]:
reload_or_model.predict(X=[[1,0]])

array([1])